spring.application.name=rent-car

# JWT
jwt.secret=YOUR_SECRET_KEY
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/rent_car
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver